# Generated by Django 2.2.4 on 2020-05-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stored', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='web_data',
            table='grayquest_web_data',
        ),
    ]
